server:
  port: 8443
  ssl:
    bundle: "collector-api"
    enabled-protocols: "TLSv1.3"

spring:
  application:
    name: collector-app
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
          show_sql: false
      jakarta:
        persistence:
          schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: ddl/create.sql
                drop-target: ddl/drop.sql
  ssl:
    bundle:
      jks:
        collector-api:
          key:
            alias: "collector-api"
          keystore:
            location: "classpath:collector-api.p12"
            password: "${KEYSTORE_PASSWORD}"
            type: "PKCS12"

