server:
  port: 8443
  ssl:
    bundle: "collector-api"
    enabled-protocols: "TLSv1.3"
logging:
  level:
    org.hibernate.tool.schema: debug
    org.hibernate.jpa: debug
spring:
  application:
    name: collector-app
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          show_sql: false
      jakarta:

        schema-generation:
          create-source: metadata
          scripts:
            action: update
            create-target: ddl\create.sql
            drop-target: ddl\drop.sql
  #  liquibase:
  #    change-log: classpath:db/changelog/dbchangelog.xml
  ssl:
    bundle:
      jks:
        collector-api:
          key:
            alias: "collector-api"
          keystore:
            location: "classpath:collector-api.p12"
            password: "${KEYSTORE_PASSWORD}"
            type: "PKCS12"
