
    create table app_user (
        enabled boolean not null,
        failed_login_attempts integer not null,
        user_id bigint generated by default as identity,
        created_at varchar(255),
        email varchar(255) not null unique,
        last_login varchar(255),
        password_hash varchar(255),
        provider varchar(255),
        provider_id varchar(255),
        updated_at varchar(255),
        username varchar(255) not null unique,
        primary key (user_id)
    );

    create table app_user_role (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table quote (
        quote_id bigint generated by default as identity,
        user_id bigint,
        author varchar(255) not null,
        quote TEXT default 'Anonymous' not null,
        primary key (quote_id)
    );

    create table role (
        role_id bigint generated by default as identity,
        role_name varchar(255),
        primary key (role_id)
    );

    alter table if exists app_user_role 
       add constraint FKsifjkys2rwyx2vnc3lunj3n1n 
       foreign key (role_id) 
       references role;

    alter table if exists app_user_role 
       add constraint FKfnlxi1bmv5ao8u3nf30ymq7xa 
       foreign key (user_id) 
       references app_user;
