
    create table app_user (
        enabled boolean,
        failed_login_attempts integer,
        user_id bigint generated by default as identity,
        created_at varchar(255),
        email varchar(255) not null unique,
        last_login varchar(255),
        password_hash varchar(255),
        provider varchar(255),
        provider_id varchar(255),
        updated_at varchar(255),
        username varchar(255) not null unique,
        primary key (user_id)
    );

    create table credentials (
        email varchar(255),
        password varchar(255),
        username varchar(255) not null,
        primary key (username)
    );
